version: '3.8'
services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
  backend:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8000:8000"

